### PR TITLE
Add Chimera Linux

### PR DESCRIPTION
**Pull request by jcgruenhage**
This is adjusted from the alpine.yaml file in the same folder, and is not tested at all.

### CODE REVIEW

**Comment by AMDmi3** [comment]
Merged in 5c7b0eb614d137b74ac05bf15f92ed2c413faba9

**Comment by jcgruenhage** [comment]
@AMDmi3 it seems like the maintainer assignment is broken. All packages are assigned to the fallback maintainer.

**Comment by AMDmi3** [comment]
It is not, repository data does not contain any maintainer information.

**Comment by jcgruenhage** [comment]
Mhmm, https://pkgs.chimera-linux.org/packages does contain some maintainer data. I'll try to take a look at some point why the index doesn't.

**Pull request closed without merging**
