### PR TITLE
openwrt: un-shadow snapshot

### PR DESCRIPTION
**Pull request by mayli**
It pretty useful to show the package status for snapshot builds.

### CODE REVIEW

**Comment by AMDmi3** [comment]
This change is no-op as openwrt snapshot repository is completely disabled anyway.

**Comment by mayli** [comment]
Any reason the snapshot repo is disabled? I think it quite useful to scan over snapshot to figure out outdated packages. It's not quite useful for current 19.07 release since lots of packages have been already updated to a newer version in snapshot.

**Comment by AMDmi3** [comment]
Yes - it doesn't behave sanely with packages disappearing and reappearing over time. We can't use that as it pollutes the feeds a lot.

**Comment by AMDmi3** [comment]
Merged. As mentioned, enabling the repo is impossible due to its unstable nature. Could use an alternative, preferrably some dump on openwrt source package metadata, but I haven't found anything like that.

**Pull request merged**
