### PR TITLE
add: bioarchlinux

### PR DESCRIPTION
**Pull request by starsareintherose**

### CODE REVIEW

**Comment by starsareintherose** [comment]
I try to fix it

**Comment by starsareintherose** [comment]
on my fork repo, test is passed

**Comment by AMDmi3** [comment]
`biology` group is not needed - that is intended for distro families. Also please squash into a single commit. Otherwise looks good.

**Comment by starsareintherose** [comment]
okay, I will  modified

**Comment by starsareintherose** [comment]
Done

**Pull request merged**
