### PR TITLE
add LiGurOS distribution

### PR DESCRIPTION
**Pull request by palica**
please add liguros distribution

thank you

### CODE REVIEW

**Comment by AMDmi3** [comment]
Is this just a merger of some overlays?

**Comment by palica** [comment]
Liguros is a collection of overlays and ebuilds used by our operating system that is a variant of Gentoo. It includes also forks and modifications and additional software projects.

Thank you very much.

**Comment by AMDmi3** [comment]
Does it contain any genuine work? I only see merges in the history.

**Comment by palica** [comment]
It depends where you are looking. The tree gets generated from http://gitlab.com/liguros/kit-fixups.git where also genuine work is taking place. The meta-repo, core-kit ... are generated kits that get their contents from overlays and our modifications.

Thank you very much.

**Comment by AMDmi3** [comment]
Merged

**Pull request closed without merging**
