### PR TITLE
Add source dev/danyspin97

### PR DESCRIPTION
**Pull request by jarun**
Ref: issue #960.

### CODE REVIEW

**Comment by AMDmi3** [comment]
There's no such repository. Since it comes from outside of git.exherbo.org it needs a special handling. But as suggested in #960 let's start from getting complete list of exherbo repositories, as others may be missing. And/or there may by a way to get all the repositories in one go I don't know about.

**Comment by jarun** [comment]
I see one difference.

For this unlisted repo the status is marked as third party: https://gitlab.exherbo.org/DanySpin97/danyspin97-exheres/blob/master/metadata/about.conf

For a listed repo, the status is dev. For example:

https://gitlab.exherbo.org/exherbo-devs/zlin/blob/master/metadata/about.conf

**Comment by jarun** [comment]
And as you mentioned, the repository is not linked as well.

**Comment by AMDmi3** [comment]
I have no idea of how the exherbo repositories are classified. If the package shows up on https://git.exherbo.org/summer/packages/ and/or in the system, there should be a list of all included repositories somewhere.

**Pull request closed without merging**
