### PR TITLE
terra: Add Terra rawhide

### PR DESCRIPTION
**Pull request by lleyton**
This adds the new Terra repo for Fedora rawhide :)

### CODE REVIEW

**Comment by AMDmi3** [comment]
String literal should be quoted, otherwise probably good.

**Comment by lleyton** [comment]
Alrightie, just did that.

**Comment by lleyton** [comment]
heya, don't mean to bother, but anything else I should change?

**Comment by lleyton** [comment]
Just added the Terra 40 repo as well, which is newly branched off

**Pull request merged**
