### PR TITLE
Add Hunter (C++ Package Manager)

### PR DESCRIPTION
**Pull request by prince-chrismc**
:wave: I would love to add support for this repository! Please let me know if anything is missing 😄 
I mainly just followed #1016 along with the changes since then... 

I followed the instruction in the README and eventually got myself setup... (please slow down with the Python updates)

image

### CODE REVIEW

**Comment by prince-chrismc** [comment]
I do have a small impediment... I can see the project in the local web app, however I am not able to run the fetch/parse enough to debug my code

```sh
$ python3.10 repology-update.py --fetch --parse --database hunter
Oct 07 15:41:46 updating repositories metadata
Oct 07 15:41:46   committing changes
Oct 07 15:41:46 not fetching hunter to honor update period (0:01:33.972174 left)
Oct 07 15:41:50 not parsing hunter due to no data changes since last run
Oct 07 15:41:50 starting the update
Oct 07 15:41:50 forcing update for projects affected by changed CPEs
Oct 07 15:41:50 updating projects
...
```

❓ is there an easy way to by pass this?

**Comment by prince-chrismc** [comment]
image

**Comment by AMDmi3** [comment]
There unfortunately are at least two show stoppers for this.
- We don't accepts new parsers which parse complex formats like shell and cmake with regexps. You can prepare machine readable dump on your side instead.
- We require valid upstream URLs, while most packages here are cloned to https://github.com/hunter-packages

**Comment by prince-chrismc** [comment]
Those are reasonable requirements. But it's not something I have control over

**Pull request closed without merging**
