### PR TITLE
Exherbo updates

### PR DESCRIPTION
**Pull request by tombriden**
* Addition of a PACKAGE_RECIPE url that's now in our packages.json
* Update urls to our new home at exherbolinux.org

### CODE REVIEW

**Comment by AMDmi3** [comment]
Right about time -  I was going to remove broken repository.
- Recipe links are broken for gitlab, these miss `/-/` before `/blob/`
- Would be nice to have links to raw recipes as well
- `LinkType` missing in `from repology.package import`

**Comment by tombriden** [comment]
> Right about time - I was going to remove broken repository.
> 
> * Recipe links are broken for gitlab, these miss `/-/` before `/blob/`
> * Would be nice to have links to raw recipes as well
The gitlab url does work without the `/-/`, which meant I could build the link in the same way for the gitlab and github repos; but yeah, it's probably best to use the correct url so have updated that and added the raw recipe urls too

> * `LinkType` missing in `from repology.package import`
oops, that's what i get for not testing it first :)

**Comment by AMDmi3** [comment]
> The gitlab url does work without the

Right, that was mispaste on my side. Anyway, is it possible to add raw recipe links as well?

**Comment by tombriden** [comment]
> > The gitlab url does work without the
> 
> Right, that was mispaste on my side. Anyway, is it possible to add raw recipe links as well?

Yep, they're in there now

**Comment by tombriden** [comment]
is this good to merge now or...?

**Comment by tombriden** [comment]
Hi @AMDmi3, is there anything more you need in this MR? I'm keen to get us back up and syncing with repology

**Comment by AMDmi3** [comment]
No, it's perfect, thank you!

**Pull request merged**
