### PR TITLE
Added src_prepare

### PR DESCRIPTION
**Pull request by y0rune**
Signed-off-by: Marcin Woźniak <y0rune@aol.com>

### CODE REVIEW

**Comment by AMDmi3** [comment]
The repository does not provide parsable package metadata (metadata/md5-cache). And I'm overall hesitant on adding this small repository without strong quality policies.

**Comment by xgqt** [comment]
> The repository does not provide parsable package metadata

Neither does GURU repo, yet you somehow parse that one.

> small repository without strong quality policies

Policies are not everything, grep for "**EAPI=4**" inside Gentoo's main repo. That's great development /s

<br />

Either way, you do what you want.

**Comment by xgqt** [comment]
https://github.com/gentoo-mirror/src_prepare-overlay/tree/master/metadata

Here is the metadata

**Comment by xgqt** [comment]
And as for policy I can give you some f stupid examples from GURU too

**Comment by AMDmi3** [comment]
> Here is the metadata

Original submission referred to different repository https://gitlab.com/src_prepare/src_prepare-overlay/-/tree/master/metadata

Either way, this repository does not met maturity requirements for repology, sorry.

**Comment by xgqt** [comment]
> > Here is the metadata
> 
> Original submission referred to different repository https://gitlab.com/src_prepare/src_prepare-overlay/-/tree/master/metadata
> 
> Either way, this repository does not met maturity requirements for repology, sorry.

Ok, thanks for cooperation.
Have a good day.

**Pull request closed without merging**
