### PR TITLE
Make the freshness map more legible by hiding colliding labels on hover

### PR DESCRIPTION
**Pull request by zopieux**
image

A real fix would be to use eg. d3js to implement zooming. Please tell me if you're interested.

### CODE REVIEW

**Comment by AMDmi3** [comment]
Wow, nice! Though I wonder if this will work on the site which has Content-Security-Policy header which prohibits builtin scripts.

**Comment by arrowd** [comment]
It'd be great to have this on the main site. What's blocking this?

**Comment by zopieux** [comment]
> It'd be great to have this on the main site. What's blocking this?

:shrug:

**Comment by AMDmi3** [comment]
Like I've said, embedded scripts and styles are prohibited by CSP, so it won't work on the site.

**Comment by zopieux** [comment]
Is your point that the embedded script should be extracted in a standalone js file instead of being embedded?

**Comment by AMDmi3** [comment]
Yes, that would work.

**Comment by AMDmi3** [comment]
@zopieux although, if you plan to work on this, we may consider adding an API endpoint which returns JSON with info for all these dots, and generate svg with JavaScript from the scratch instead of moving pregenerated svg objects around. This could allow to conveniently explore the while graph at once given that the points are unevenly distributed. But, I'll happily merge any solution - as said, CSP issue is the only thing that blocks this.

**Comment by zopieux** [comment]
Eh, this CL celebrated its 4 year anniversary eleven days ago, so sadly I won't be giving it any more love. Anyone is very much welcome to take it over though.

**Pull request closed without merging**
