### PR TITLE
add gentoo science overlay

### PR DESCRIPTION
**Pull request by epsilon-0**
Adds the science project from Gentoo - https://wiki.gentoo.org/wiki/Project:Science

Related - https://github.com/repology/repology-updater/issues/1078

### CODE REVIEW

**Comment by AMDmi3** [comment]
Sorry, this is not acceptable without metadata.

**Comment by epsilon-0** [comment]
@AMDmi3 
if metadata were added, would it be possible to add this?

**Comment by epsilon-0** [comment]
OK, so this metadata generation is stopped because of our current outdated state of the science repository.

Would it be possible to keep this open while we are fixing the repository and finish generating the metadata?

**Comment by epsilon-0** [comment]
@AMDmi3 
I'm a bit confused on what you meant by **metadata**, but I've updated the link with the URL which contains the `md5-cache`.

Is this fine?

Thanks!

**Comment by AMDmi3** [comment]
Yes, this is good. Thanks! Will deploy after adding some rules as this repository introduces a handful of new project name clashes.

**Comment by epsilon-0** [comment]
@AMDmi3 
Thanks a lot!!!
:heart: :heart: :heart: :heart:

**Pull request merged**
