### PR TITLE
Add Rocky Linux 9 & update sources/groups/lifetimes of CentOS/Rocky/Alma

### PR DESCRIPTION
**Pull request by robert-scheck**
See also: https://rockylinux.org/news/rocky-linux-9-0-ga-release/

### CODE REVIEW

**Comment by AMDmi3** [comment]
Could you please enlighten me a bit regarding these subrepositories? Are these enabled by default in fresh Rocky installation? Is there a list somewhere for each release? Do other centos clones need similar changes?

**Comment by robert-scheck** [comment]
Red Hat Enterprise Linux **8 and 9** (e.g. SKUs RH00003, RH00004, RH00005) have only two default repositories: **BaseOS** and **AppStream**, the same applies to Rocky Linux 8 and 9.

RHEL 8 and 9 also have an optional repository (= not enabled by default) called "CodeReady Linux Builder". Given this is a Red Hat trademark, CentOS Linux **8** called it **PowerTools** (and Rocky Linux 8 reuses this name). However, CentOS Stream **9** calls it **CRB** (and Rocky Linux 9 reuses this name).

Not every RHEL derivative provides the following repositories, for different (internal) reasons:

RHEL 8 and 9 have different paid socalled **Add-On**s, effectively resulting in separate optional repositories (= not enabled by default):

  * High Availability Add-On (e.g. SKU RH00025), Rocky Linux 8 and 9 call this **HighAvailability** repository
  * Resilient Storage Add-On (e.g. SKU RH00026), Rocky Linux 8 and 9 call this **ResilientStorage** repository

Then, there is the "Red Hat Enterprise Linux for Real Time" product (e.g. SKU RH00394), effectively resulting in a separate optional repository (= not enabled by default), that's called **RT** (and Rocky Linux 9 reuses this name).

And there are "Red Hat Enterprise Linux for SAP Applications" product (e.g. SKU RH00159) and "Red Hat Enterprise Linux for SAP Solutions" product (e.g. SKU RH00764), which also effectively result in separate optional repositories (= not enabled by default), one is **SAP**, the other is **SAPHANA** (I don't know which one is which, because I'm fortunately not running or administrating any SAP product).

There also is a "Red Hat Solution for NFV" to serve as layers for the European Telecommunication Standards Institute (ETSI) NFV model, e.g. as "Red Hat Enterprise Linux Real Time for NFV" (no idea which SKU this is), effectively resulting in a separate optional repository (= not enabled by default), that's called **NFV** (and Rocky Linux 9 reuses this name).

The **extras** repository was introduced by CentOS Linux to e.g. provide the "epel-release" RPM package in a repository; Rocky Linux has inherited this.

See also:
  * https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/package_manifest/repositories
  * https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/package_manifest/index
  * https://access.redhat.com/rhel-real-time-getting-started
  * https://access.redhat.com/solutions/3082481
  * https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.0/html/director_installation_and_usage/planning-your-overcloud

**Comment by robert-scheck** [comment]
Does this answer your questions? Or shall I split up the pull request into multiple ones? Just let me know, please.

**Comment by AMDmi3** [comment]
Merged, thank you!

Could you please add sources of EoL dates (in form of commented urls near corresponding configs)?
And Eurolinux misses EoL dates, would be nice to add these too if possible.

**Pull request closed without merging**
